creation_rules:
  - gcp_kms: projects/containerization-441901/locations/us-east5/keyRings/my-keyring/cryptoKeys/my-key
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yaml$'
    encrypted_regex: '^(data)$'