apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: db-namespace
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:99FO1VlgLpHQr3N6cpzoAg==,iv:kL1reKSlrbYvrPDzz+yhkaYPkGL3DflmdFZ9j1iYr3Q=,tag:WG1yFpzEKTOlP03hf6WwMg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:RRQXk0rV/QJQgwAX,iv:jjAhElvpxPt6GZ9CaE6hMWEI+xF4TMRjcas05/kEKmA=,tag:hdW1AqY66bIwwfO2rSQy9A==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:txLufPNNLCi9Puti,iv:823mYIqVVHFDXkFxeihJS4JBJwK//1K7CNOpOCpQw7k=,tag:HxBvEcxaJKc8kM+TZ4NqEA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/containerization-441901/locations/us-east5/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-11-16T16:43:26Z"
          enc: CiQAFOmJkb9sHIyyKCOZhEDCQPFcHUics7Dpph1DHHlm2wkh3tsSSQB9CTlgvDUiYEG9WvlMWc+73a1ADs4a9vYtnwO6ZTApgQjSrWI+VnPotfoUC25mfSvd9PA0OYkCvGw/RbPYuPx5V4v+oSMMgJQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T16:43:26Z"
    mac: ENC[AES256_GCM,data:LG8F+dM3vkLIbd5Mc03LThN2ht8F8wNLpWwDEUrjHgQI0Tc5wy+J6h9wx/GaSGGuJvLIRfYjy+GBY4COdnyZWOubi9aPZ+SHsypYVJ2PMNoWlzML2XnOdCHz6R+fEbceIfo9BjDBGCnnEgX6okantjRh0cz0NgTSi1H2+lD2T3Y=,iv:c9KkxFe+LGumM/Max6ruJZ01xLY/kM9D3dz/ojGXiwg=,tag:S0ujtgrz+k/L3E+GmhivqA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
