apiVersion: v1
kind: Secret
metadata:
    name: wp-secret
    namespace: wp-namespace
type: Opaque
data:
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:UEnQgJAuZ7tyR9ge,iv:8NYNjwCNIFHACd+UPqLy/P1llCWY6MyvQjpaplgNCUs=,tag:H9NH7jM/bDyreejgXNsgwA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/containerization-441901/locations/us-east5/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-11-16T16:43:35Z"
          enc: CiQAFOmJkemvvcjEdrnA7aajIv5+P30TP6uYFjQmJZwF+K02tzQSSQB9CTlgkPVmJCH97ZMsCnaRYEV00GDu8ng4doDXQDnqYn2OLmXxezOwZhZlkpG+4+3e4lOU5TXMwfaf6CW2k4AnP7Xh8HdZYxg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T16:43:35Z"
    mac: ENC[AES256_GCM,data:VdD5Kjdp/79lIahQDZQ+QcZJ12m2DlTDw6W4rpngQOzOfHP5/siXduXenG/OzNdtYf4WTzWZMPlOWzjbSa7EaOjws1zr5EqyOXbAtw07sRchbNWl88MdN5rkKvwwdyKuu5poVppyfw5q6i2Cju+pMR7TbNRXnWPNIGLQuNaV3Ek=,iv:SoUGrl3wfYtuhnqQARED/Yg8wOaZRv7iGsJCljXCu+0=,tag:HAAFWm24sBpHIYQ0ZN82KA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
