apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: proxy-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      id: C0916072
  template:
    metadata:
      labels:
        id : C0916072
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: gcr.io/containerization-441901/nginx_proxy2:latest
        ports:
        - containerPort: 80

